spring:
  config:
    import: optional:secrets.yml
  application:
    name: flyme
  r2dbc:
    username: faroc
    password: changeit
    url: r2dbc:postgresql://localhost:5432/flyme
  flyway:
    user: faroc
    password: changeit
    url: jdbc:postgresql://localhost:5432/flyme
    locations: classpath:/db/migration
springdoc:
  packages-to-scan: com.faroc.flyme
  group-configs:
    - group: V1
      paths-to-match:
        - /v1/**
airport-gap:
  api-url: https://airportgap.com/api/